### ISSUE TITLE
statsr R/rep_sample_n.R breaks windows installs

### ISSUE THREAD

**Issue by thoughtfulbloke** [StatsWithR/statsr#1]
At time of writing, rep_sample_n.R has non-breaking spaces as the indentation of lines 12 to 17. A lot of Windows OS character sets just can't cope with this and it breaks on an unrecognised symbol during the install process, as it substitutes other characters (depending on what the OS characters thinks the symbols are) 

The easiest fix I can see is to replace the first two non-breaking spaces in lines 12 to 17 with ascii spaces

**Comment by pmembrey** [comment]
It also breaks on Manjaro Linux.

**Comment by bhunkeler** [comment]
Yep, I came to the same conclusion as thoughtfulbloke. Spaces need to be replaced.

**Comment by mine-cetinkaya-rundel** [comment]
I think this should now be fixed. I confirmed on a Windows computer as well. Let me know if issues persist.

PS: Some issue with my settings meant I didn't get an email when this was first posted. I'll fix that now so that further issues can be attended more quickly. Thanks for bringing it to my attention.
